### ISSUE TITLE
error in SublimeLinter daemon

### ISSUE THREAD

**Issue by tijs** [SublimeLinter/SublimeLinter-flow#28]
I have installed the flow linter in SublimeText 3 together with the latest version of flow (0.22.0) and am running into the following issue. When the linter runs, i save a file with the `/* @flow */` directive added, it simply throws the error below.

I made sure i don't have any other flow plugins installed. Flow runs fine from the command line. No sure what else this could be.

```
SublimeLinter: flow activated: /usr/local/bin/flow 
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/tijs/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tijs/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/Users/tijs/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/Users/tijs/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/tijs/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 924, in lint_view
    linter.lint(hit_time)
  File "/Users/tijs/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1367, in lint
    cmd = self.get_cmd()
  File "/Users/tijs/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1112, in get_cmd
    cmd = self.cmd()
  File "linter in /Users/tijs/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-flow.sublime-package", line 52, in cmd
KeyError: 'use-server'
 
SublimeLinter: -------------------- 
```

**Comment by m6g6a** [comment]
+1

**Comment by andrefgneves** [comment]
+1

**Comment by andrefgneves** [comment]
I got it working by adding `"use-server": false` to my `SublimeLinter.sublime-settings`

**Comment by ckaznocha** [comment]
This should be all set now.

**Comment by tijs** [comment]
i added the "use-server" attribute to my settings as @andrefgneves suggested and that did the trick for me! thanks @ckaznocha

**Comment by ckaznocha** [comment]
Glad it's working for you @tijs. With the latest update adding the "use-server" setting should no longer be needed but leaving it there won't harm anything.
