### ISSUE TITLE
KeyError: 'level' - error in SublimeLinter daemon

### ISSUE THREAD

**Issue by sharq1** [SublimeLinter/SublimeLinter-flow#36]
This is what I get in ST3 console:
```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/damian/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/damian/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/Users/damian/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/Users/damian/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/damian/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 924, in lint_view
    linter.lint(hit_time)
  File "/Users/damian/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 77, in lint
    super(NodeLinter, self).lint(hit_time)
  File "/Users/damian/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1397, in lint
    for match, line, col, error, warning, message, near in self.find_errors(output):
  File "linter in /Users/damian/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-flow.sublime-package", line 80, in _error_to_tuple
KeyError: 'level'
 
SublimeLinter: -------------------- 
```

I have flow installed globally in "/usr/local/bin/flow"
Running flow in my project directory produces correct output in console
This is my config:
```
"flow": {
    "@disable": false,
    "args": [],
    "excludes": [],
    "show-all-errors": true
},
```

**Comment by alathon** [comment]
Having the same issue. Flow is installed globally, although the project also has a local version of flow - both the node_modules/.bin/flow and the global flow run just fine.

Here is the Debug-enabled output from SublimeLinter:

```
1 problem 
SublimeLinter: flow: Counter.js ['/home/alathon/workspace/some-proj/node_modules/.bin/flow', '--show-all-errors', '--json'] 
SublimeLinter: flow output:
{"flowVersion":"0.23.0","errors":[{"operation":{"context":"yodawg('Hi')","descr":"function call","type":"Blame","loc":{"source":"/home/alathon/workspace/some-proj/src/components/Counter/Counter.js","type":"SourceFile","start":{"line":17,"column":1,"offset":227},"end":{"line":17,"column":12,"offset":239}},"path":"/home/alathon/workspace/some-proj/src/components/Counter/Counter.js","line":17,"endline":17,"start":1,"end":12},"kind":"infer","level":"error","message":[{"context":"  return x * 10","descr":"string","type":"Blame","loc":{"source":"/home/alathon/workspace/some-proj/src/components/Counter/Counter.js","type":"SourceFile","start":{"line":13,"column":10,"offset":216},"end":{"line":13,"column":10,"offset":217}},"path":"/home/alathon/workspace/some-proj/src/components/Counter/Counter.js","line":13,"endline":13,"start":10,"end":10},{"context":null,"descr":"This type is incompatible with","type":"Comment","path":"","line":0,"endline":0,"start":1,"end":0},{"context":"  return x * 10","descr":"number","type":"Blame","loc":{"source":"/home/alathon/workspace/some-proj/src/components/Counter/Counter.js","type":"SourceFile","start":{"line":13,"column":10,"offset":216},"end":{"line":13,"column":15,"offset":222}},"path":"/home/alathon/workspace/some-proj/src/components/Counter/Counter.js","line":13,"endline":13,"start":10,"end":15}]}],"passed":false} 
SublimeLinter: flow 1 errors. passed: False 
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/home/alathon/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alathon/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/home/alathon/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/home/alathon/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/home/alathon/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 924, in lint_view
    linter.lint(hit_time)
  File "/home/alathon/.config/sublime-text-3/Packages/SublimeLinter/lint/node_linter.py", line 77, in lint
    super(NodeLinter, self).lint(hit_time)
  File "/home/alathon/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1397, in lint
    for match, line, col, error, warning, message, near in self.find_errors(output):
  File "linter in /home/alathon/.config/sublime-text-3/Installed Packages/SublimeLinter-flow.sublime-package", line 80, in _error_to_tuple
KeyError: 'level'
```

**Comment by betacode** [comment]
The Flow output JSON might have changed in version 0.23.0
here is the current format as you can see "level" has moved up to where message is.
{
      "kind": "infer",
      "level": "error",
      "message": [

I was able to fix this by changing line 80 in linter.py
from: level = error_messages[0]['level']
to: level = error.get('level', '')

not sure what the final fix would look like but with this fix the plugin now works for me.

**Comment by ckaznocha** [comment]
Hey @betacode code, if you'd like to submit a PR with your fix I'd be happy to accept it. I think the solution is to update the minimum flow version requirement for the next release to be 0.23.0. Folks with an older version of flow can update flow or stick with the current version of the linter.
