### ISSUE TITLE
queue.Empty and KeyError: ''

### ISSUE THREAD

**Issue by alfredxing** [SublimeLinter/SublimeLinter-flow#38]
The linter is throwing these exceptions at me whenever it's linting. Looking in the console, it seems like everything was parsed correctly... though I'm not too sure with how SublimeLinter works (you'll probably have a better idea).

I'm running at all default settings, latest Flow.

Here are the console errors:

```
SublimeLinter: -------------------- 
SublimeLinter: flow: test.js ['/usr/local/bin/flow', '--show-all-errors', '--json'] 
SublimeLinter: flow output:
{"flowVersion":"0.24.2","errors":[{"kind":"infer","level":"error","message":[{"context":"function add(a: int, b: int): int {","descr":"identifier `int`","type":"Blame","loc":{"source":"/Users/alfredxing/Desktop/test/test.js","type":"SourceFile","start":{"line":7,"column":17,"offset":49},"end":{"line":7,"column":19,"offset":52}},"path":"/Users/alfredxing/Desktop/test/test.js","line":7,"endline":7,"start":17,"end":19},{"context":null,"descr":"Could not resolve name","type":"Comment","path":"","line":0,"endline":0,"start":1,"end":0}]}],"passed":false} 
SublimeLinter: flow 1 errors. passed: False 
SublimeLinter: flow line: 6, col: 16, level: error, message: identifier `int` Could not resolve name 
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/alfredxing/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alfredxing/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/Users/alfredxing/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/Users/alfredxing/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/alfredxing/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 962, in lint_view
    callback(cls.get_view(vid), linters, hit_time)
  File "/Users/alfredxing/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 167, in highlight
    highlights.draw(other_view)
  File "/Users/alfredxing/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/highlight.py", line 98, in draw
    all.draw(view)
  File "/Users/alfredxing/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/highlight.py", line 390, in draw
    self.set_mark_style()
  File "/Users/alfredxing/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/highlight.py", line 377, in set_mark_style
    self.mark_flags = MARK_STYLES[self.mark_style]
KeyError: ''
 
SublimeLinter: --------------------
```

**Comment by ckaznocha** [comment]
Hey @alfredxing the cause is not jumping out at me. Are you getting this issue with other flow errors? What version of the the linter and SublimeLinter are you running?

**Comment by ckaznocha** [comment]
Also by any chance do you have SublimeLinter configured to use some gutter style that's not supported by your set up?

**Comment by alfredxing** [comment]
I don't think so... I never changed any settings. I'm using the linter from master (I cloned the git repo into Packages for debugging), and SublimeLinter 3.7.4.

Let me know if I can do anything to provide more information (I can add log lines to the code, or change the code, etc.)

**Comment by ckaznocha** [comment]
Do you have other linters that are working correctly?

**Comment by alfredxing** [comment]
That's a good question! I honestly haven't tried any other one out before. I just did (eslint) and it has the same issue, so I'll close this one and open one up in the main SublimeLinter repo.

Thanks for your help!
